# Consignas
- 1 Generar un array de 3 dimensiones y mostrar el output en una captura de pantalla.
- 2 Ubicar el valor de un elemento en el array de 3 dimensiones con la función correspondiente y compartir el output en una captura de pantalla.
- 3 Utilizando append, agregamos 3 valores nuevos al array y compartamos output en una captura de pantalla.
- 4 Generar un nuevo array de 3 dimensiones, pero con el formato requerido para que el output en una captura de pantalla pueda mostrarnos un resultado como (3,3) usando shape.
- 5 Ahora, con la librería de pandas, crear una serie llamada (marcas_productos) y compartir el output en una captura de pantalla donde pueda mostrarnos la lista.
- 6 Generar una nueva serie llamada (color_cantidad) utilizando index para generar o modificar la columna inicial. Luego, compartir el output en una captura de pantalla donde pueda mostrarnos la lista con los nombres de la columna. "Azul", "Blanco", "Celeste", "Negro", "Rojo".
  
## Entrega
Se debe adjuntar una imagen o screenshot (captura de pantalla) de cada ejercicio que responda a cada pregunta.
¡Llegamos al final de la actividad de este módulo! Recordemos guardar las respuestas y luego subirlas haciendo clic en el botón "Enviar tarea".
Recordemos que es posible consultar las dudas con nuestros compañeros en el foro de la materia o con nuestro tutor.

### Consigna 1
- 1 Generar un array de 3 dimensiones y mostrar el output en una captura de pantalla.

In [32]:
import numpy as np
three_dimensions_list = [[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]]
array = np.array(three_dimensions_list)
print(array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Consigna 2
- 2 - Ubicar el valor de un elemento en el array de 3 dimensiones con la función correspondiente y compartir el output en una captura de pantalla.

In [5]:
element = array[0,0,0]
print(element)

1


### Consigna 3
- 3 - Utilizando append, agregamos 3 valores nuevos al array y compartamos output en una captura de pantalla.

In [13]:
np.append(array, (101, 102, 103))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12, 101,
       102, 103])

### Consigna 4
- 4 - Generar un nuevo array de 3 dimensiones, pero con el formato requerido para que el output en una captura de pantalla pueda mostrarnos un resultado como (3,3) usando shape.

In [26]:
new_two_dimensions = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
new_three_dimensions = np.array([[[1, 1, 1], [2, 2, 2], [3, 3, 3]], [[4, 4, 4], [5, 5, 5], [6, 6, 6]], [[7, 7, 7], [8, 8, 8], [9, 9, 9]]])
print(new_two_dimensions.shape)
print(new_three_dimensions.shape)

(3, 3)
(3, 3, 3)


### Consigna 5
- 5 - Ahora, con la librería de pandas, crear una serie llamada (marcas_productos) y compartir el output en una captura de pantalla donde pueda mostrarnos la lista.

In [29]:
import pandas as pd

marcas_productos = pd.Series()

print(marcas_productos)

Series([], dtype: object)


### Consigna 6
- 6 - Generar una nueva serie llamada (color_cantidad) utilizando index para generar o modificar la columna inicial. Luego, compartir el output en una captura de pantalla donde pueda mostrarnos la lista con los nombres de la

In [30]:
color_cantidad = pd.Series([7,5,3],index=['Amarillo','Azul','Rojo'])
print(color_cantidad)

Amarillo    7
Azul        5
Rojo        3
dtype: int64


In [33]:
a = np.array([[5, 3, 6], [7, 9, 5]])
b = np.array([[4, 6, 3], [2, 1, 10]])

print(a*b)

[[20 18 18]
 [14  9 50]]
